version: "2"
services:
  senaite:
    image: senaite
    volumes:
    - data:/data
    environment:
    - ADDONS=senaite.core senaite.storage senaite.core.listing senaite.core.supermodel senaite.impress senaite.lims senaite.health
    ports:
    - "8080:8080"

volumes:
  data:
